version: "3"
services:
  web_prod:
      build:
         context: .
         target: prod
      env_file: ./.env
      environment:
      - NODE_ENV=production
      container_name: node-snapshare
      restart: always
      command: npm run start
      volumes: 
         - .:/app/
         - /app/node_modules
      ports:
          - "80:5000"