version: "3"
services:
  web_dev:
      build:
         context: .
         dockerfile: Dockerfile.dev
         target: dev
      env_file: ./.env
      container_name: dev-node-snapshare
      command: npm run dev
      volumes: 
         - .:/app/
         - /app/node_modules
      ports:
      - 8080:8080