version: "3"
services:
  web_dev:
      build:
         context: .
      env_file: ./.env
      command: npm run dev
      volumes: 
         - .:/app/
         - /app/node_modules
      ports:
      - 8080:8080